{
  "swagger": "2.0",
  "info": {
    "title": "My API",
    "description": "Description",
    "version": "1.0.0"
  },
  "host": "localhost:3000",
  "basePath": "/",
  "schemes": [
    "http"
  ],
  "paths": {
    "/hello": {
      "get": {
        "description": "",
        "parameters": [],
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      }
    },
    "/order-process/{id}": {
      "get": {
        "description": "",
        "parameters": [],
        "responses": {}
      }
    },
    "/order-process": {
      "post": {
        "description": "",
        "parameters": [],
        "responses": {}
      },
      "put": {
        "description": "",
        "parameters": [],
        "responses": {}
      }
    },
    "/order-process/product/{valor}": {
      "get": {
        "description": "",
        "parameters": [],
        "responses": {}
      }
    }
  }
}